[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103bc9350>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/72b3ce8c59947c2dd9870d2dcf59ba44
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103bc89d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/72b3ce8c59947c2dd9870d2dcf59ba44
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103ad8390>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/72b3ce8c59947c2dd9870d2dcf59ba44