[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4A587D280>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/883c4f38f436044648ebe93e15d51035
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4A587D100>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/883c4f38f436044648ebe93e15d51035
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B4A587DD30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/883c4f38f436044648ebe93e15d51035